name: infinite_loop_list
description: "A simple and lightweight Flutter widget for creating **infinite looping lists** with optional **auto-scroll** support.  
Perfect for carousels, banners, news tickers, and any scrollable content that should repeat infinitely."
version: 1.0.0
homepage: https://github.com/fluttersample/flutter_infinite_loop_list


publish_to: "https://pub.dev"


environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


